### PR TITLE
Drop in for discussion

### PR DESCRIPTION
**Pull request by rafaelchiti**
Hey folks, question, maybe this is documented somewhere else, or there is a or a better approach to tackle what I share below, if that's the case feel free to ignore and close this PR!.

I wonder if we have some details/context explained somewhere about this Fork. Any info that would help someone that bumps into this down the road and needs to understand why we forked or how to package or whether we can converge back to using the original version again?

cc @bywo @framp you might have context?

### CODE REVIEW

**Comment by bywo** [comment]
the changes are all mine. I needed to make a code change to support better styling of date range selections in the calendar.

the diff is pretty small: https://github.com/wojtekmaj/react-calendar/compare/master...classdojo:master

**Comment by bywo** [comment]
oh cool, my PR got merged. so we can go back to mainline: https://github.com/wojtekmaj/react-calendar/pull/373

just need to tweak the classnames in our our CSS files.

**Comment by rafaelchiti** [comment]
oh nice, cool contribution :)

**Comment by bywo** [comment]
resolved with https://github.com/classdojo/web-monorepo/commit/a7dfb61293b642fc669688083328b74e2a2f6f48

**Pull request closed without merging**
